/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import bean.ProductoBean;
import bean.VentaBean;
import datos.ProductoDAO;
import datos.ProductoDAOFileImpl;
import datos.VentaDAO;
import datos.VentaDAOFileImpl; 
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.JTable;
import java.util.ArrayList;
import java.sql.Timestamp;
import java.util.Date;
import java.util.HashMap; 
import java.util.Vector;


/**
 *
 * @author alexis
 */
public class MainWindow extends javax.swing.JFrame {
    
    private ProductoDAO productoDAO;
    private VentaDAO ventaDAO;
    private boolean isEditting;
    private DefaultTableModel lista_venta;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setTitle("Applicator v1.0");
        this.productoDAO = new ProductoDAOFileImpl("productos.dat");
        this.ventaDAO = new VentaDAOFileImpl("ventas.dat");
        String[] columnNames = {"Código","Nombre","Cantidad",};
        this.lista_venta = new DefaultTableModel(columnNames, 0);
        this.clearTF();
        this.isEditting = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        TF_precio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        B_guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF_stock = new javax.swing.JTextField();
        TF_codigo = new javax.swing.JTextField();
        TF_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        L_retroalimentacion = new javax.swing.JLabel();
        B_Editar = new javax.swing.JButton();
        B_Eliminar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_productos_disponibles = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Spinner_Cantidad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        B_Agregar_Producto = new javax.swing.JButton();
        Label_Venta = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        List_productos_disponibles = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_productos_venta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TF_precio.setToolTipText("");
        TF_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_precioActionPerformed(evt);
            }
        });

        jLabel2.setText("Código");

        B_guardar.setText("Guardar/Limpiar");
        B_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_guardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel4.setText("Stock");

        TF_stock.setToolTipText("");
        TF_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_stockActionPerformed(evt);
            }
        });

        TF_codigo.setEditable(false);
        TF_codigo.setToolTipText("");
        TF_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_codigoActionPerformed(evt);
            }
        });

        TF_nombre.setToolTipText("");
        TF_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_nombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Precio");

        L_retroalimentacion.setText("...");

        B_Editar.setText("Editar");
        B_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EditarActionPerformed(evt);
            }
        });

        B_Eliminar.setText("Eliminar");

        jTable_productos_disponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_productos_disponibles.setEditingColumn(0);
        jTable_productos_disponibles.setEditingRow(0);
        jTable_productos_disponibles.setUpdateSelectionOnSort(false);
        jScrollPane4.setViewportView(jTable_productos_disponibles);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(L_retroalimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(B_guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(B_Editar)
                                .addGap(35, 35, 35)
                                .addComponent(B_Eliminar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TF_stock, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(TF_precio, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TF_codigo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TF_nombre, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(27, 27, 27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(L_retroalimentacion)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TF_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TF_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Eliminar)
                    .addComponent(B_Editar)
                    .addComponent(B_guardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Producto", jPanel3);

        jButton1.setText("Remover Producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Realizar Venta");
        jButton2.setMaximumSize(new java.awt.Dimension(137, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(137, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Cantidad");

        B_Agregar_Producto.setText("Agregar Producto");
        B_Agregar_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Agregar_ProductoActionPerformed(evt);
            }
        });

        List_productos_disponibles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(List_productos_disponibles);

        jTable_productos_venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable_productos_venta);
        if (jTable_productos_venta.getColumnModel().getColumnCount() > 0) {
            jTable_productos_venta.getColumnModel().getColumn(0).setResizable(false);
            jTable_productos_venta.getColumnModel().getColumn(1).setResizable(false);
            jTable_productos_venta.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Spinner_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B_Agregar_Producto))
                            .addComponent(Label_Venta))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Spinner_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Agregar_Producto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(Label_Venta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)))
        );

        jTabbedPane3.addTab("Venta", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HashMap<Integer, Integer> detalle = new HashMap();
        for(Object row : lista_venta.getDataVector()){ 
            Vector _row = (Vector) row;
            
            Integer codigo = (Integer) _row.get(0);
            Integer cantidad = (Integer) _row.get(2);
            
            detalle.put(codigo, cantidad);
            
            ProductoBean producto = this.productoDAO.obtenerProducto(codigo);
            producto.setStock(producto.getStock() - cantidad);
            this.productoDAO.modificarProducto(producto);
        }
        
        VentaBean venta = new VentaBean();
        venta.setTimestamp(new Timestamp(new java.util.Date().getTime()));
        venta.setLíneasDeDetalle(detalle);
        
        lista_venta.setRowCount(0);
        
        Label_Venta.setText("Se ha realizado la venta correctamente");
        
        this.ventaDAO.agregarVenta(venta);
        this.clearTF();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lista_venta.removeRow(jTable_productos_venta.getSelectedRow());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void B_Agregar_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Agregar_ProductoActionPerformed
        String nombreElementoSeleccionado = (String)List_productos_disponibles.getSelectedValue();
        
        jTable_productos_venta.setModel(lista_venta);
        
        for (ProductoBean bean : this.productoDAO.listarProductos()) {
            if( nombreElementoSeleccionado == bean.getNombre() ){
                Integer cantidad = (Integer)Spinner_Cantidad.getValue();
                if (bean.getStock() >= cantidad && cantidad != 0){
                    Object[] row = {bean.getCódigo(), bean.getNombre(), cantidad};
                    lista_venta.addRow(row);
                }
                else if(cantidad == 0){
                    Label_Venta.setText("La cantidad debe ser mayor a 0");
                }
                else{
                    Label_Venta.setText("No hay stock suficiente");
                }
            }
        }        
    }//GEN-LAST:event_B_Agregar_ProductoActionPerformed

    private void B_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EditarActionPerformed
        TF_nombre.setEditable(true);
        TF_codigo.setEditable(true);
        TF_precio.setEditable(true);
        TF_stock.setEditable(true);
        
        this.mostrarProductoSeleccionado();
        
        this.isEditting = true;
    }//GEN-LAST:event_B_EditarActionPerformed

    private void mostrarProductoSeleccionado(){
        Integer códigoElementoSeleccionado = (Integer)jTable_productos_disponibles.getValueAt(jTable_productos_disponibles.getSelectedRow(), 0);
        
        ProductoBean bean = this.productoDAO.obtenerProducto(códigoElementoSeleccionado);
        if(bean!=null){
            TF_nombre.setText(bean.getNombre());
            TF_codigo.setText(String.valueOf(bean.getCódigo())) ;
            TF_precio.setText(String.valueOf(bean.getPrecio()));
            TF_stock.setText(String.valueOf(bean.getStock()));
            this.isEditting = true;
        }
    }
    
    private void TF_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_nombreActionPerformed

    private void TF_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_codigoActionPerformed

    private void TF_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_stockActionPerformed

    private void B_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_guardarActionPerformed
        if(!TF_nombre.getText().trim().isEmpty() && !TF_precio.getText().trim().isEmpty() && !TF_stock.getText().trim().isEmpty()){
            ProductoBean producto = new ProductoBean();
            producto.setNombre(TF_nombre.getText());
            producto.setCódigo(Integer.valueOf(TF_codigo.getText()));
            producto.setPrecio(Integer.valueOf(TF_precio.getText()));
            producto.setStock(Integer.valueOf(TF_stock.getText()));
            if(this.isEditting){
                this.productoDAO.modificarProducto(producto);
                L_retroalimentacion.setText("La base de datos ha sido actualizada.");
            }else{
                if(this.productoDAO.agregarProducto(producto)){
                    L_retroalimentacion.setText("La base de datos ha sido actualizada.");
                }else{
                    L_retroalimentacion.setText("¡La base de datos no ha sido actualizada!");
                }
            }
            this.clearTF();
        }else{
            L_retroalimentacion.setText("Faltan campos por completar.");
        }
    }//GEN-LAST:event_B_guardarActionPerformed

    private void TF_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_precioActionPerformed

    private void clearTF(){
        this.isEditting = false;
        TF_nombre.setEditable(true);
        TF_codigo.setEditable(true);
        TF_precio.setEditable(true);
        TF_stock.setEditable(true);
        
        TF_nombre.setText("");
        TF_codigo.setText(String.valueOf(this.productoDAO.obtenerCódigoMásAltoDeProducto()+1));
        TF_precio.setText("");
        TF_stock.setText("");
        
        String[] columnNames = {"Código","Nombre","Stock","Precio (CLP$)"};
        DefaultTableModel dtm = new DefaultTableModel(columnNames, 0);
        DefaultListModel dlm = new DefaultListModel();
        
        List<ProductoBean> tmp = this.productoDAO.listarProductos();
        for (ProductoBean bean : tmp) {
            Object[] row = {bean.getCódigo(),bean.getNombre(),bean.getStock(),bean.getPrecio()};
            dtm.addRow(row);
            dlm.addElement(bean.getNombre());
       }
        
        jTable_productos_disponibles.setModel(dtm);
        List_productos_disponibles.setModel(dlm);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Agregar_Producto;
    private javax.swing.JButton B_Editar;
    private javax.swing.JButton B_Eliminar;
    private javax.swing.JButton B_guardar;
    private javax.swing.JLabel L_retroalimentacion;
    private javax.swing.JLabel Label_Venta;
    private javax.swing.JList List_productos_disponibles;
    private javax.swing.JSpinner Spinner_Cantidad;
    private javax.swing.JTextField TF_codigo;
    private javax.swing.JTextField TF_nombre;
    private javax.swing.JTextField TF_precio;
    private javax.swing.JTextField TF_stock;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable_productos_disponibles;
    private javax.swing.JTable jTable_productos_venta;
    // End of variables declaration//GEN-END:variables
}